export const data = [
  {
    title: 'intro',
    text: 'León Ferrari (September 3, 1920 – July 25, 2013) was an Argentine contemporary conceptual artist. During his extended art career (1954-2013), his artworks often protested the Argentinian government, the imperialist west, and the Church. Ferrari began his career by making small drawings, but primarily did sculptures until 1962, when he began to employ his life-long motif of language and scratchy, calligraphic writing. Ferrari created protest art using collage, photocopying and sculpture in wood, plaster, wire and ceramics. He often used text, especially newspaper clippings or poetry, particularly in his pieces protesting the Church and the Argentinian government. His art often dealt with the subject of political power and religion. Some of his most controversial images depicted saints, the Virgin Mary, and Jesus found in toasters or microwaves, on nude figures, or being defecated on by live birds. He deals with issues of United States foreign policy with the Vietnam War in his best-known work, La civilización occidental y cristiana (Western-Christian Civilization, 1965). In this work, Christ appears crucified on a fighter plane, as a symbolic protest against the Vietnam War and Western Imperialism.',
  },
  { title: 'early works', text: '' },
  {
    title: 'language and writing',
    text: "Starting in 1962, Ferrari began to use language and letters as a common theme in many artworks. Scholars point to multiple influences as explanations for Ferrari's interest in words. One reason is that his young daughter lost her ability to hear due to meningitis and had to be taught language differently by her parents. Another reason is that Argentinian political thought within the public sphere was largely controlled by a corrupt media at this time, so Ferrari wanted to present words through art as a different medium for language in protest against the media. Ferrari's reasoning for using this medium has also been said to \"question the distinction between art and language—between pure visuality and codified information, and between graphic gesture and calligraphy.\" Ferrari did not always use language in intelligible ways. For instance, he would sometimes just use lines and letters to create the image of text, as in his piece Reflections from 1963-64. Another famous example of his unintelligible writing is Ferrari's famous piece Carta a un general (Letter to a General). This piece is written in a very loose, calligraphic style that does not allow the viewer to clearly read the message. This piece represented Ferrari's thoughts that effective communication with a political power (such as a dictatorial general) is impossible. However, when he did write intelligibly, it was often in essay, letter, or poetic forms, transcribing his thoughts on politics, current events, or his own artwork. These pieces were still written in a sloppy, calligraphic style, however one would be able to make out the words much more clearly. An example of this is the piece titled Cuadro escrito that he made in which he responds to the critiques of his exhibit at the Torcuato di Tella Institute National Prize exhibition in 1965.",
  },
  {
    title: 'abstention',
    text: 'After playing such a central role in heated, highly politicized protest art, Ferrari took a hiatus from art-making. Although he may have been making art during these years, his works were not appearing in the public sphere. In addition to this, Ferrari had been heavily involved in the political protest scene of Argentina in the 1960s. He may have made the decision to lay low for a while following highly dynamic period of protest, which included his participation in Tucumán Arde. In 1976, Ferrari departed the country and entered a period of exile in São Paulo, Brazil.',
  },
  {
    title: 'heliografias',
    text: 'Following a period of mostly unintelligible, scratchy drawing, Ferrari entered a period of print-making, creating his famous series known as "Heliografías." These works were sketches and designs for absurd urban plans, including city plans, freeway designs, neighborhood maps, furniture layouts, and other, more simplistic patterns. Ferrari is quoted explaining these Heliograph artworks: "These works express the absurdity of contemporary society, that sort of daily madness necessary for everything to look normal." Along with this concept of absurdity, scholars suggest Ferrari desired to point out the dangers of blindly following a pattern or movement. He created prints where small figures were trapped inside a closed loop, moving forward in the loop but never moving out. With this idea of blindly choosing uniformity, Ferrari hoped to draw ties to the way many Argentinians simply ambivalently allowed injustice to continue with their blind adherence to the status quo.[5] Occasionally within these prints, Ferrari would switch the pattern, such as in his piece Adulterio (Adultery), where a white king breaks the pattern and sleeps with a black queen. This was meant just to ask the question: what if we break the pattern?',
  },
  {
    title: 'body',
    text: 'In 1997, Ferrari created two series using braille. In the first, he took lines from the poems and stories of famous Argentinian writer Jorge Luis Borges, and emboss the words in Braille on erotic or nude photographs. In the second series, Ferrari used verses of scripture embossed in braille. In both cases, the idea was to force viewers to touch or, as Ferrari often described, "caress" the naked bodies depicted in the prints in order to understand the words written on the image. An example of this is Ferrari\'s piece titled La Serpiente in which a Japanese stamp has been reprinted, depicting a couple engaged in sex. The words "la serpiente me engaño y comí," which is Genesis 3:13, (translated: "the serpent deceived me, and I ate") are embossed in braille over the area in the image where the couples\' genitals come together. Ferrari created these artworks often as a way to push back against the Church\'s demonization of women, sexuality, and often of homosexuality.',
  },
  {
    title: 'christian',
    text: 'In the early 2000s, Ferrari exhibited a series of artworks using small, plastic figures of Christian figures, including Jesus, the Virgin Mary, and various Saints. He placed these figurines inside what he deemed "hot situations" including microwaves, blenders, and frying pans.',
  },
];
